### PR TITLE
Adopt JRE8, hold JRE7

### PR DESCRIPTION
**Pull request by gheine**

### CODE REVIEW

**Comment by arbjerg** [comment]
+1

**Comment by gheine** [comment]
PS I wasn't quite sure what section this belongs to. Certainly not "programming language" because this is about the Java 8 runtime platform only and not the language, so I put it into the "deployment" section. Thoughts?

**Comment by andreyk0** [comment]
👍

**Comment by zcohn** [comment]
👍

**Comment by fiadliel** [comment]
Might be worth mentioning that Scala 2.12 will only support Java 8+.

**Pull request merged**
