### PR TITLE
Gerrit -> Hold.

### PR DESCRIPTION
**Pull request by andreyk0**
Recommend creation of the new repos in GH.

### CODE REVIEW

**Comment by trenaman** [comment]
+1

**Comment by gheine** [comment]
🉑

**Comment by andreyk0** [comment]
^^ @gheine is that a yes or a no? :)

**Comment by gheine** [comment]
@andreyk0 funny, I asked that same question recently. Apparently, somewhere someone made up the rule that "each emoji counts as a +1"

**Comment by andreyk0** [comment]
;( So, this is a +1 ?

**Comment by andreyk0** [comment]
😕 ah, I suppose that one isn't but maybe this one is?

**Comment by gheine** [comment]
Yes, it's a +1. Sorry for the confusion! :)

**Comment by andreyk0** [comment]
Haha, cool!
🙈 🔫 :metal:

**Comment by grahamar** [comment]
Definitely since -> https://github.com/blog/2141-squash-your-commits

**Comment by arbjerg** [comment]
I have never been a gerrit fan, however I am a big fan of developer productivity, so after having thought about it for a while, I very much feel like this recurring discussion about gerrit vs. github are both **pointless** and a waste of time. If certain teams work better with gerrit, let them!  I do realize that there is some maintenance required by infra, however, I don't get the sense that it's all the bad...

**Comment by arbjerg** [comment]
by the way, that's a -1 from me :)

**Comment by zcohn** [comment]
@arbjerg I agree -- I don't see a reason to change behavior around this, but if this is just documenting a norm that has already changed, I think it makes sense. The question is: are folks still creating new gerrit repos and we are trying to discourage them, or have people (and this is my sense) independently already moved to github and we are just reflecting that back to the organization. This is a bit of an empirical question, perhaps a gerrit admin can weigh in.

**Comment by njprrogers** [comment]
+1

**Pull request merged**
