### PR TITLE
Assess Aurora for Postgres

### PR DESCRIPTION
**Pull request by gheine**

### CODE REVIEW

**Comment by mkows** [comment]
Are there any specific reasons from your POV @gheine to use Aurora instead of standard RDS PostgreSQL?
Btw. does `Aurora` work with `Schema evolution manager`?

**Comment by gheine** [comment]
@mkows Amazon claims that Aurora is more performant than RDS Postgres. It's fully compatible and thus triggers and stored procedures for pg should all work with Aurora. That would include sem. But we haven't used it yet, so it needs "assessing" :)

**Comment by kevinoriordan** [comment]
@nemo83 did some investigation and concluded that the Amazon performance numbers were cherry-picked to make Aurora seem a lot more performant than it actually is. Might be some improved replication functionality that makes it worthwhile though.

**Comment by gheine** [comment]
Moved to https://github.com/saksdirect/tech-radar/pull/18

**Pull request closed without merging**
