### PR TITLE
Scraping --> ADOPT

### PR DESCRIPTION
**Pull request by kevinoriordan**

### CODE REVIEW

**Comment by k4sbasia** [comment]
👍

**Comment by gheine** [comment]
:trollface:

**Comment by umatrangolo** [comment]
:+1 

I think I saw this also on the ThoughtlessnessWorks tech radar.

**Comment by arbjerg** [comment]
Is this April Fools!?

**Comment by andreyk0** [comment]
LOL

**Comment by arbjerg** [comment]
Very funny!

**Pull request closed without merging**
