### PR TITLE
Kotlin language: assess -> adopt

### PR DESCRIPTION
**Pull request by sullis**
reference:  https://www.theverge.com/2017/5/17/15654988/google-jet-brains-kotlin-programming-language-android-development-io-2017

### CODE REVIEW

**Comment by andreyk0** [comment]
Do we have any production Kotlin android code? If not - perhaps it should stay in 'Assess' until we actually try it out for real.

**Comment by gheine** [comment]
I agree with Andrey. We should have at least assessed it once successfully before moving it "up the ladder". Next would be "trial" anyway, before "adopt".

**Comment by umatrangolo** [comment]
👍

**Comment by chavdarch** [comment]
👍

**Comment by gheine** [comment]
Moved to https://github.com/saksdirect/tech-radar/pull/19

**Comment by sullis** [comment]
ApiBuilder added Kotlin support in August 2017:

https://github.com/apicollective/apibuilder-generator/commit/25bfcd77ed45a46895cd1a62285fee256860b9be#diff-d5b12207172bf3ba606c64ff27f3c5ef

**Pull request closed without merging**
