### PR TITLE
Cave to HOLD

### PR DESCRIPTION
**Pull request by umatrangolo**

### CODE REVIEW

**Comment by andreyk0** [comment]
👍

**Comment by gheine** [comment]
+1

**Comment by brazir** [comment]
Everyone is in favor.  Think that scripting should be made or patchsets offered to ease the transition off of cave to cloudwatch/ newrelic custom reporting / graphana.  Cloudwatch also has some highly available reporting that came out as a new feature. Perhaps spend the time to covert the cave client to send metrics cloudwatch as a quick transfer.  Semantics seem one-to-one compatible with cloudwatch.

**Comment by rlmartin** [comment]
@brazir One callout where the semantics are different: tagging. In CAVE, you can tag metrics and either roll-up the totals or break them out based on tag. In CloudWatch, they have the idea of Dimensions - these look like of like tags but do not work the same way because Dimensions cannot be rolled up to the root metric (to me they feel more like individual metrics). In this particular instance, I've always preferred CAVE's approach to CloudWatch's.

**Comment by jkenny** [comment]
You would also need to migrate svc-healthcheck alerts, which are configured
for all legacy services.

**Comment by gheine** [comment]
HOLD first and foremost means: don't use any more than you're already using it, ie. don't add any new cave metrics or cave-instrument new services. Transition of existing cave clients to cloudwatch, prometheus or whatever is somewhat orthogonal.

**Pull request merged**
