### PR TITLE
Added serverless Lambda. Operating System -> Operating Platform.

### PR DESCRIPTION
**Pull request by arbjerg**

### CODE REVIEW

**Comment by arbjerg** [comment]
Note, this is a *very* different context for Lambda, as we currently only have it in the "deployment" section .  This is meant as using Lambda in the true sense of "servelessness" (whatever that is...)

**Comment by umatrangolo** [comment]
Can't see any issue with this. 👍

**Comment by gheine** [comment]
Sounds good, though I'm not sure whether it makes sense to expand the scope of recommendations on "Operating Systems" to "Operating Platforms" to squeeze in Lambda. Would Docker (listed under Deployment") not fall into this category too then? What is the argument against listing AWS Lambda only in the Deployment section?

**Comment by arbjerg** [comment]
=> Execution Environment

**Pull request merged**
