### PR TITLE
Trial Nova, hold sbt-code-deploy

### PR DESCRIPTION
**Pull request by gheine**

### CODE REVIEW

**Comment by zcohn** [comment]
👍

**Comment by RoryH** [comment]
👍

**Comment by andreyk0** [comment]
👍

**Comment by rcaloras** [comment]
👍 LGTM

**Comment by brazir** [comment]
This project was part of the evolution of tooling work that the supply team had gone through.  It was a collaboration between several teams in order to standardize.  The goal was to make it generic as possible to deploy.  In practice it wound up with a number of rough edges that made it easy to add, but hard to maintain.  The original developers left the company or the project and attempts at upgrades by myself and proman resulted in the conclusion that it was not worth continuing to pursue.  The supply team has been following up with basic scripts for aws as a replacement and as a result this project is dead.

LGTM to the commit.

**Pull request merged**
