### PR TITLE
GoLang --> Trial

### PR DESCRIPTION
**Pull request by umatrangolo**

### CODE REVIEW

**Comment by gheine** [comment]
👎  If we're considering advocating natively compiled languages, I'd much prefer a recommendation for a more fp language like Haskell or Rust. But my reservations about Go aside, this should at most be in the asses category, given how little experience we have with it so far.

**Comment by umatrangolo** [comment]
Looking forward to a proposal about Haskell or Rust. In the meanwhile there is something that already addresses a concern we raised in the last Arch Council (non JVM solutions) that runs in Production as we speak (svc-shipping-address).

**Comment by arbjerg** [comment]
Voted to assess

**Comment by gheine** [comment]
@umatrangolo mind updating the PR (trial -> assess) and merging afterwards?

**Pull request merged**
