### PR TITLE
Revert "Update Deployment.md"

### PR DESCRIPTION
**Pull request by zcohn**
Not actually a proposal to revert, just the simplest way to ensure this change was tracked for discussion.

### CODE REVIEW

**Comment by grahamar** [comment]
👍  didn't realise, CONTRIBUTING didn't seem to mention anything about the discussion...

**Comment by andreyk0** [comment]
Haha, @grahamar is unstoppable! :)

**Comment by zcohn** [comment]
Some folks might say that you should read the entire README before merging to master 😀 
`Changes to standards need to get architecture board's approval`
Although it would be a little more convincing if that weren't a broken link 👹

**Comment by gheine** [comment]
+1 :)

**Comment by grahamar** [comment]
@zcohn I did read that, but it doesn't specify that 2 arch board members +1'ing it doesn't count...

**Pull request closed without merging**
