### PR TITLE
Specify Docker registry recommendation.

### PR DESCRIPTION
**Pull request by vdumitrescu**

### CODE REVIEW

**Comment by andreyk0** [comment]
:+1:

**Comment by gheine** [comment]
:+1: Looks great!

**Comment by gheine** [comment]
Voted For: 7, Against: 0, Abstained: 0

**Comment by trenaman** [comment]
Key points  in the discussion: given the different version of the registry and lack of backward compatibility, it doesn't make sense to run this centrally. Running locally in each account will be easier; and, eventually, when AWS releases this as a service, then we'll recommend migrating to the SaaS solution provided by AWS.

**Pull request merged**
